config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :posts

  root 'posts#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup', to: 'users#new', as: :signup
  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout
  
  get '/posts', to: 'posts#index', as: :posts
  get '/posts/filter/:category_id', to: 'posts#filter', as: :filtered_posts
  get '/posts/new', to: 'posts#new', as: :new_post
  get '/posts/:id', to: 'posts#show', as: :post
  post '/posts', to: 'posts#create'
  get '/posts/:id/edit', to: 'posts#edit', as: :edit_post
  patch '/posts/:id', to: 'posts#update'
  delete '/posts/:id', to: 'posts#delete'


  get '/categories', to: 'categories#index', as: :categories
  get '/categories/new', to: 'categories#new', as: :new_category
  get '/categories/:category_id', to: 'categories#show', as: :category
  post '/categories', to: 'categories#create'
  get '/categories/:category_id/edit', to: 'categories#edit', as: :edit_category
  patch '/categories/:category_id', to: 'categories#update'
  delete '/categories/:category_id', to: 'categories#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify

  validates :name, presence: true, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category

  scope :ordered, -> { order(id: :desc) }
  scope :with_categories, -> { includes(:category) }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_categories
    before_action :authorized
    before_action :authorized_admin
    helper_method :current_user
    helper_method :logged_in?
    helper_method :logged_in_admin?

    def current_user
        User.find_by(id: session[:user_id])
    end
    def logged_in?
           
        !current_user.nil?
    end
    def authorized
       redirect_to '/login' unless logged_in?
    end

    def logged_in_admin?
        !current_user.nil?  && current_user.email == 'super_admin'
    end
    
    def authorized_admin
       redirect_to '/login' unless logged_in_admin?
    end

    private
 
    def set_categories
        @categories = Category.all
    end

    end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authorized, only: [:index, :show, :load_category]
  skip_before_action :authorized_admin
  def index
    @categories = Category.all
  end

  def show
    load_category
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to @category
  end

  def edit
    load_category
  end

  def update
    load_category
    @category.update(category_params)
    redirect_to :category
  end

  def delete
    load_category
    @category.destroy
    redirect_to :categories
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def load_category
    @category = Category.find(params[:category_id])
  end
end

app/controllers/navbar_controller.rb
class NavbarController < ApplicationController
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authorized, only: [:filter, :index, :show]
  skip_before_action :authorized_admin
  def index
    @posts = Post.all
  end

  def show
    load_post
  end

  def filter
    @category = Category.find( params[:category_id])
    @posts = Post.where(category_id: params[:category_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to @post
  end

  def edit
    load_post
  end

  def update
    load_post
    @post.update(post_params)
    redirect_to :post
  end

  def delete
    load_post
    @post.destroy
    redirect_to :posts
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :category_id)
  end

  def filter_param
    params.require(:category_id)
  end

  def load_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  skip_before_action :authorized_admin
  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      
      render "new", alert: "Logged in!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorized, only: [:new, :create]
  skip_before_action :authorized_admin, only: [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/posts">BLOG</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Posts
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to 'All posts', posts_path, class: 'dropdown-item' %>
        <div class="dropdown-divider"></div>
        <% @categories.each do |category| %>
            <%= link_to category do %>
              <%= link_to category.name, filtered_posts_path(category), class: 'dropdown-item' %>
            <% end %>
        <% end %> 
      </div>
    </li>

    <%= link_to 'Categories', categories_path, class: 'nav-link' %>
  </ul>

  <div class="d-flex ml-lg-4">
    <% if current_user %>
      <%= link_to 'Log Out', logout_path, class: "btn btn-outline-success" %>
      <div class="user-info ml-1">Logged in as <br> <%= current_user.email %></div>
    <% else %>
      <%= link_to 'Sign Up', signup_path, class: "btn btn-outline-success"%> 
      <%= link_to 'Log In', login_path, class: "btn btn-outline-success ml-1" %>
    <% end %>
  </div>
</div>
</nav>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit category "<%= @category.name %>"</h1>
<%= render partial: 'form' %>
<div class="link-container">
  <%= link_to 'Back to categories', categories_path %>
</div>

app/views/categories/index.html.erb
<h1>All categories</h1>
<%= link_to "Create new category", new_category_path, class: 'ml-5 btn btn-success' %>
<div class="posts-container">
  <% @categories.each do |category| %>
    <div class="category">

      <%= link_to category do %>
        <h3> <%= category.name %> </h3>
      <% end %>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= render partial: 'form' %>
<div class="link-container">
  <%= link_to 'Back to categories', categories_path %>
</div>

app/views/categories/show.html.erb
<h1> <%= @category.name %> </h1>

<div class="link-container">
  <%= link_to 'Edit', edit_category_path(@category.id) %>
</div>
<div class="link-container">
  <%=
    link_to 'Delete', category_path(@category.id), method: :delete,
      data: { confirm: "Are you sure?" }, remote: true
  %>
</div>
<div class="link-container">
  <%= link_to 'Back to categories', categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial =>'navbar', locals:   {categories: @categories} %>
    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%>
  <div class="form-group">
    <%= f.label :title%>
    <%= f.text_field :title, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.select :category_id, Category.all.map { |c| [c.name, c.id] } , class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/_list.html.erb
<div class="row justify-content-between">
  <% @posts.each do |post| %>
    <div class="col-11 col-md-5 card col-xl-4 card mt-2" style="width: 300px;">
      <div class="card-body">
       <%= link_to post do %>
          <h4 class="card-title"><%= post.title %></h4>
        <% end %>
        <h6 class="card-subtitle mb-2 text-muted"><%= post.category.name %></h6>
        <p class="card-subtitle mb-2 text-muted"><%= post.created_at %></p>
        <p class="card-text text-truncate" style="height:55px"><%= post.text %> </p>
        <%= link_to 'Edit', edit_post_path(post.id),class: 'card-link' %>
        <%= link_to 'Delete', post_path(post.id), method: :delete,
          data: { confirm: "Are you sure?" }, remote: true, class: 'card-link'
        %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit post "<%= @post.title %>"</h1>
<%= render partial: 'form' %>
<div class="link-container">
  <%= link_to 'Back to posts', posts_path %>
</div>

app/views/posts/filter.html.erb
<h1>All posts related to <%= @category.name %> category</h1>
<%= link_to "Create new post", new_post_path, class: 'ml-5 btn btn-success' %>
<%= render partial: 'list' %>

app/views/posts/index.html.erb
<h1>All posts</h1>
<%= link_to "Create new post", new_post_path, class: 'ml-5 btn btn-success' %>
<div class="container">
    <%= render partial: 'list' %>

</div>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render partial: 'form' %>
<div class="link-container">
  <%= link_to 'Back to posts', posts_path %>
</div>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<p> <%= @post.category.name %> </p>
<p> <%= @post.created_at %> </p>
<p> <%= @post.text %> </p>

<div class="link-container">
  <%= link_to 'Edit', edit_post_path(@post.id) %>
</div>
<div class="link-container">
  <%=
    link_to 'Delete', post_path(@post.id), method: :delete,
      data: { confirm: "Are you sure?" }, remote: true
  %>
</div>
<div class="link-container">
  <%= link_to 'Back to posts', posts_path %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>